MODEL_NAME='CNN'
#MODEL_NAME='GRU'
#MODEL_NAME='LSTM'


CPT_PATH = '../model/ads/checkpoints/'+MODEL_NAME+'/0'
LOG_PATH='../log/ads/'+MODEL_NAME+'/data0.txt'


VOCAB_SIZE=4567
UNK_ID = 0
PAD_ID = 1
START_ID = 2
EOS_ID = 3

NUM_STEPS=20
NUM_LAYERS = 2
HIDDEN_SIZE = [128,128]
BATCH_SIZE = 128
LR = 0.0003
#NUM_SAMPLES = 512
NUM_CLASSES=3
EMBEDDING_SIZE=256
KERNEL_SIZE=[2,3,4]
NUM_FILTERS=2
DROPOUT_KEEP_PROB=0.3

READ_IN_FORMAT=[[0]]*(NUM_STEPS)
ONE_HOT_TAG=False
EPOCH_NUM = 1000

PRETRAIN_EMBD_TAG=False
PRETRAIN_EMBD_TRAINABLE=False
PRETRAIN_EMBD_SIZE=50
PRETRAIN_EMBD_VOCAB_SIZE = 400002
PRETRAIN_EMBD_PATH ='../data/glove.6B.50d.txt'

SELF_ATTENTION_TAG = False
ATTENTION_SIZE = 15
NUM_TOPICS =4
ATTENTION_COEF=0.004

HIERACHICAL_ATTENTION_TAG=False

MODEL_BI_DIRECTION = True
INITIALIZER='xavier'
